### ISSUE TITLE
Cannot convert to ASCII

### ISSUE THREAD

**Issue by laszukdawid** [olemb/dbfread#18]
I'm having problems tables with unicode. `CNTR_AT_2013` comes from [Eurostat db](http://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/countries). Below is my attempt to read data and what is expected (parsed via Unix `dbfview`).

Problems occurs both in Python 2.7 and 3.5.

```
>>> for record in dbfread.DBF('CNTR_AT_2013.dbf'):
           print record
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dbfread/dbf.py", line 316, in _iter_records
    for field in self.fields]
  File "/usr/local/lib/python2.7/dist-packages/dbfread/field_parser.py", line 79, in parse
    return func(field, data)
  File "/usr/local/lib/python2.7/dist-packages/dbfread/field_parser.py", line 87, in parseC
    return self.decode_text(data.rstrip(b'\0 '))
  File "/usr/local/lib/python2.7/dist-packages/dbfread/field_parser.py", line 45, in decode_text
    return decode_text(text, self.encoding, errors=self.char_decode_errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)
>>> table = dbfread.read("CNTR_AT_2013.dbf")
/usr/local/lib/python2.7/dist-packages/dbfread/deprecated_dbf.py:47: UserWarning: dbfread.read() has been replaced by DBF(load=True) and will be removed in 2.2.
  warnings.warn("dbfread.read() has been replaced by DBF(load=True)"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dbfread/deprecated_dbf.py", line 49, in read
    return DeprecatedDBF(filename, load=True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dbfread/dbf.py", line 136, in __init__
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/dbfread/deprecated_dbf.py", line 18, in load
    self[:] = self._iter_records(b' ')
  File "/usr/local/lib/python2.7/dist-packages/dbfread/dbf.py", line 316, in _iter_records
    for field in self.fields]
  File "/usr/local/lib/python2.7/dist-packages/dbfread/field_parser.py", line 79, in parse
    return func(field, data)
  File "/usr/local/lib/python2.7/dist-packages/dbfread/field_parser.py", line 87, in parseC
    return self.decode_text(data.rstrip(b'\0 '))
  File "/usr/local/lib/python2.7/dist-packages/dbfread/field_parser.py", line 45, in decode_text
    return decode_text(text, self.encoding, errors=self.char_decode_errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)
```

```
Cntr id    : QN
Cntr name  : Puerto Rico and Virgin Islands of the United States
Name asci  : Puerto Rico and Virgin Islands of the United States
Name engl  : Puerto Rico and Virgin Islands of the United States
Name fren  : PUERTO RICO ET LES ÎLES VIERGES DES ÉTATS-UNIS
Poli org c : 99.00000000
Name gaul  : 
Iso3 code  : 
Svrg un    : US Territory
Capt       : 
Cntr code  : UA
Eu stat    : F
Efta stat  : F
Cc stat    : F

Cntr id    : QO
Cntr name  : Guadeloupe and Martinique
Name asci  : Guadeloupe and Martinique
Name engl  : GUADELOUPE AND MARTINIQUE
Name fren  : GUADELOUPE ET MARTINIQUE
Poli org c : 99.00000000
Name gaul  : 
Iso3 code  : 
Svrg un    : FR Territory
Capt       : 
Cntr code  : UA
Eu stat    : F
Efta stat  : F
Cc stat    : F
```

**Comment by olemb** [comment]
From the error message and data you included it looks like the file uses utf-8, where"É" is encoded as 0xc389:

```
>>> 'É'.encode('utf-8')
b'\xc3\x89'
```

Here's how you can choose encoding:

```
for record in dbfread.DBF('CNTR_AT_2013.dbf', encoding='utf-8'):
    print(record)
```

**Comment by laszukdawid** [comment]
It works. I haven't noticed the <strong>encoding</strong> option. Thanks!

**Comment by olemb** [comment]
I'm happy to hear that!
